refactor: removes feeDistro.claimToken call from helper
aurafinance/aura-contracts pull request #107
Opened 2022-07-25 11:09 UTC by 0xahtle7

2022-07-26 12:59 UTC, 0xMaharishi approved these changes

2022-07-26 12:59 UTC, 0xMaharishi requested changes
Fix failing CI. Other than that, LGTM

2022-07-26 19:48 UTC, 0xahtle7 commented on README.md
> +| BoosterHelper                   | [0x64b8A7f32b928cB87E05804b112aD55DD7297e20](https://etherscan.io/address/0x64b8A7f32b928cB87E05804b112aD55DD7297e20) |
This will be updated after the deployment

2022-07-26 19:48 UTC, 0xahtle7 commented on contracts/ClaimFeesHelper.sol
> -     * @param _feeDistro    FeeDistro e.g. 0xA464e6DCda8AC41e03616F95f4BC98a13b8922Dc
shall we update on the code base all references to 0xA464e6DCda8AC41e03616F95f4BC98a13b8922Dc?

2022-07-27 15:36 UTC, 0xMaharishi approved these changes

2022-07-27 17:42 UTC, merged